### ISSUE TITLE
Problemas na liçao de Lógica

### ISSUE THREAD

**Issue by tomatebio** [tomatebio/R_iniciante#1]
Pessoal, 

 Apareceu um problema na lição de Lógica. Agora está tudo certo. Para conseguir a versão arrumada reinstale a curso.

# Isso vai desinstalar todos os cursos que você tiver no computador

uninstall_all_courses(force=T)

# Agora você instala normalmente 
install_course_github("tomatebio","Programando_em_R")

**Comment by ramirbjunior** [comment]
Vlw! Comecei as atividades há pouco tempo e percebi que essa etapa de Lógica estava apresentando problemas.
