### ISSUE TITLE
bibliometrix

### ISSUE THREAD

**Issue by ramirbjunior** [tomatebio/R_iniciante#4]
Alguém teve problemas com o pacote bibliometrix? 
Ele apresentou problemas com dependência de outros pacotes.

**Comment by ElisaRMA** [comment]
Qual é a mensagem de erro que vc ta tendo? Eu tive problemas no Rmarkdown pra gerar PDF, mas consegui resolver.

**Comment by ramirbjunior** [comment]
Eu não usei o Rmarkdown ainda.
O erro do bibliometrix é o seguinte: 
"Warning in install.packages :
  dependency ‘fpc’ is not available
also installing the dependencies ‘rio’, ‘curl’, ‘openssl’, ‘dendextend’, ‘car’, ‘httr’, ‘factoextra’, ‘FactoMineR’, ‘rscopus’"

Esse pacote "fcp" aparentemente só funciona na versão 3.6 do R, não sei se mais alguém teve o mesmo problema. Eu uso linux e aparentemente não ta dando para instalar o R 3.6 por aqui.

**Comment by ElisaRMA** [comment]
Eu instalei e ele nao deu problema, mas usei o codigo: install.packages("bibliometrix", dependencies=TRUE, repos = "http://cran.us.r-project.org") e o meu sistema é Windows, pode ser isso.

**Comment by ramirbjunior** [comment]
Eu também havia usado o comando para instalar todas as dependências, mas não foi... O problema era o "fpc" que necessita do R >= 3.6. Consegui contornar isso no Windows, eu uso dual-boot (Windows e Ubuntu juntos). De toda forma, obrigado pelas informações.

**Comment by may321** [comment]
> Qual é a mensagem de erro que vc ta tendo? Eu tive problemas no Rmarkdown pra gerar PDF, mas consegui resolver.

Oi Elisa, como vc conseguiu resolver? Obrigada
